DB_Seeding-update agreement assigned offer types
catenax-ng/tx-portal-backend pull request #101
Opened 2023-01-18 20:12 UTC by jjeroch

2023-01-18 20:13 UTC, jjeroch commented
@evegufy & @Phil91  I changed the file name and updated the content. Not a urgent PR

2023-01-19 08:10 UTC, Phil91 requested changes

2023-01-19 08:10 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreement_assigned_offer_types.json
> +    "agreement_id": "aa0a0000-7fbc-1f2f-817f-bce0502c1092",
The agreementId isn't yet existing in the files, therefore the migratory currently runs into an error

2023-02-07 21:52 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreement_assigned_offer_types.json
> +    "agreement_id": "aa0a0000-7fbc-1f2f-817f-bce0502c1092",
fixed; it must be 91 instead of 92

2023-02-07 21:53 UTC, jjeroch commented
@Phil91  can you help me out with the branch conflict?

2023-02-08 11:19 UTC, Phil91 commented
> @Phil91 can you help me out with the branch conflict?

Sure, I'll have a look at it and test it again

2023-02-08 13:57 UTC, Phil91 approved these changes

2023-02-08 15:26 UTC, merged