CPLP-1986 checklist
catenax-ng/tx-portal-backend pull request #108
Opened 2023-01-23 07:07 UTC by Phil91

This PR resolves [CPLP-1986](https://jira.catena-x.net/browse/CPLP-1986) & [CPLP-1987](https://jira.catena-x.net/browse/CPLP-1987)

2023-01-24 23:43 UTC, ntruchsess requested changes

2023-01-24 23:43 UTC, ntruchsess commented on src/checklist/Checklist.Worker/ChecklistExecutionService.cs
>                      await checklistRepositories.SaveAsync().ConfigureAwait(false);
now that more than only a single remote call might be executed it's mandatory to save the changes to each corresponding checklist-entry right after executing the step. Otherwise the next step might be cancelled discarding all database changes while the remote call already has been made.
I suggest to ensure save is called from the uppermost level HandleChecklistProcessing returns IAsyncEnumerable<bool>, that IAsyncEnumerable being iterated from CheckListExecutionService.ExecuteAsync and save being called when the boolean value from the IAsyncEnumerable is true. (HandleChecklistProcessing would execute the steps with each iteration of the IAsyncEnumerable)

2023-01-25 07:11 UTC, Phil91 commented on src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
> +            throw new ArgumentException($"CompanyApplication {applicationId} is not in status SUBMITTED", nameof(applicationId));
thanks for the changes to ConflictException

2023-01-25 08:52 UTC, Phil91 commented on src/externalsystems/Custodian.Library/CustodianService.cs
> +    public async IAsyncEnumerable<WalletListItem> GetWalletsAsync([EnumeratorCancellation] CancellationToken cancellationToken)
valid point, removed it but saved it locally for later usage

2023-01-25 08:52 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/DependencyInjection/ApplicationActivationSettings.cs
> +            case true when !settings.EndTime.HasValue:
thanks. adjusted

2023-01-25 08:52 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        var startDate = now.Date + startTime;
very good point! validation added

2023-01-25 08:53 UTC, Phil91 commented on src/checklist/Checklist.Worker/ChecklistExecutionService.cs
>                      await checklistRepositories.SaveAsync().ConfigureAwait(false);
Hope i understood it right. Should be correct now.

2023-01-25 19:32 UTC, ntruchsess approved these changes
changed from #123 are transferred into this PR. Unit-tests adjusted for IAsyncEnumerable execution of ProcessChecklist. From my point of view ready to merge. @Phil91 please double-check

2023-01-26 08:40 UTC, merged