CPLP-1988-removing-companyShortNameException
catenax-ng/tx-portal-backend pull request #128
Opened 2023-01-27 05:58 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1988

2023-01-27 08:48 UTC, ntruchsess requested changes

2023-01-27 08:48 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferService.cs
> -        if (string.IsNullOrWhiteSpace(results.Single(x => x.IsIamUser).CompanyShortName))
just to remove the check in the code is not sufficient as the column 'Provider' is not nullable in the database.
options are:
- remove non-nullable constraint on the database-column (my preference)
- store a default-value instead
please clarify with @jjeroch how to proceed

(please be aware that the query 'GetCompanyUserWithIamUserCheckAndCompanyShortName' is implemented incorrectly as it returns non-nullable 'string' instead of nullable 'string?' for the shortname which does not match the data-model. This needs to be changed both in the signature of the query-method and in the selection (replace 'companyUser.Company!.Shortname!' by 'companyUser.Company!.Shortname' removing the trailing '!')

2023-01-27 09:00 UTC, VPrasannaK94 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> -        if (string.IsNullOrWhiteSpace(results.Single(x => x.IsIamUser).CompanyShortName))
Ok Norbet , Thanks for the update.

2023-02-01 21:32 UTC, ntruchsess approved these changes

2023-02-01 21:48 UTC, merged