feature/CPLP-1107-setReleaseDate-approveOfferRequestAsync
catenax-ng/tx-portal-backend pull request #131
Opened 2023-01-27 09:55 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1107

2023-01-30 08:01 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            offer.DateReleased = DateTimeOffset.UtcNow;
We have a newly created IDateTimeProvider we could use for this. @ntruchsess what's your opinion? If we want to leave it like it is I will approve the PR

2023-02-01 21:46 UTC, ntruchsess requested changes

2023-02-01 21:46 UTC, ntruchsess commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
> +       offer.DateReleased.Should().BeSameDateAs(datetimeUTC.Date);
that is not a valid test as only Date is being compared. In case the test starts before midnight updating the offer after midnight it will fail.

2023-02-01 21:46 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            offer.DateReleased = DateTimeOffset.UtcNow;
I agree, as the test is broken (it eventually fails when run over midnight) we should use the IDateTimeProvider to have a mock-datetime in the test.

2023-02-02 22:42 UTC, ntruchsess approved these changes

2023-02-02 22:42 UTC, merged