feat(checklist): Add endpoint to get checklistDetails
catenax-ng/tx-portal-backend pull request #134
Opened 2023-01-30 07:39 UTC by Phil91

Refs: CPLP-2048

2023-02-01 22:05 UTC, ntruchsess requested changes

2023-02-01 22:05 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +             .Select(x => new ValueTuple<bool, IEnumerable<(ApplicationChecklistEntryTypeId, ApplicationChecklistEntryStatusId, string?)>>(
As there will be new TypeId ApplicationChecklistEntryTypeId.APPLICATION_ACTIVATION https://github.com/catenax-ng/tx-portal-backend/blob/f776ff41b145c50dfb362dc5c30d44d707e264d0/src/portalbackend/PortalBackend.PortalEntities/Enums/ApplicationChecklistEntryTypeId.cs#L30 we need to filter the types that shall be displayed. (From my point of view showing an ChecklistItem for the Application-activation would make sense, we need to clarify with @jjeroch. Technically I did add this type when unifying processing of the worker treating the activation as just another process-step)

2023-02-02 11:53 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +             .Select(x => new ValueTuple<bool, IEnumerable<(ApplicationChecklistEntryTypeId, ApplicationChecklistEntryStatusId, string?)>>(
after clarification with @jjeroch filter for ApplicationActivation is added

2023-02-02 11:56 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ApplicationChecklistEntryTypeIdExtensions.cs
> +    public static bool IsAutomated(this ApplicationChecklistEntryTypeId entryTypeId) =>
I moved it to the extensions to Checklist.Library since the Array is in the Worker

2023-02-02 22:17 UTC, ntruchsess approved these changes

2023-02-02 22:38 UTC, ntruchsess approved these changes

2023-02-02 22:38 UTC, merged