fix(ApplicationActivation): Remove registration client roles
catenax-ng/tx-portal-backend pull request #137
Opened 2023-01-30 14:29 UTC by Phil91

Removes the companyUser assigned roles for a specific clientId while activating the company

Refs: [TEST-522](https://jira.catena-x.net/browse/TEST-522)

2023-02-01 22:47 UTC, ntruchsess requested changes

2023-02-01 22:47 UTC, ntruchsess commented on src/checklist/Checklist.Worker/Program.cs
> +      FlurlUntrustedCertExceptionHandler.ConfigureExceptions(urlsToTrust);
for a production-system it's is a security-issue to ignore untrustworthy certificates, so this must be configurable to disable for non-dev environments.

2023-02-01 22:47 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +            var roleNamesToDelete = iamClientIds.ToDictionary(clientId => clientId, _ => userData.RolesToDelete.Select(x => x.UserRoleText));
What do we need a dictionary for if keys are assigned to the same value? Technically the provisionmanager expects the dictionary but assigning the same roles to all clients ain't work for multiple clientIds.
To get the correct mapping the query needs to include the ClientClientId a CompanyUserRole is associated with in the result.

2023-02-02 11:25 UTC, Phil91 commented on src/checklist/Checklist.Worker/Program.cs
> +      FlurlUntrustedCertExceptionHandler.ConfigureExceptions(urlsToTrust);
check for dev env added

2023-02-02 11:25 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +            var roleNamesToDelete = iamClientIds.ToDictionary(clientId => clientId, _ => userData.RolesToDelete.Select(x => x.UserRoleText));
ClientClientId added to the userRoles

2023-02-02 11:26 UTC, Phil91 commented
I`ve fixed the ApplicationActivation UnitTests besides of adding a new one for the deletion.
The merge now will merge the PR against #138 not main

2023-02-02 20:15 UTC, ntruchsess requested changes

2023-02-02 20:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                         companyUserAssignedRole.UserRole!.Offer!.AppInstances.Select(x => x.IamClient!.ClientClientId)
as this is highly redundant in the db-resultset it's probably more efficient to run separate queries. One that retrieves the roles with related data (id, userRoleText, clientClientIds) and one for users+assigned roleids in separate queries.

2023-02-03 12:29 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +    public Task SetRegistrationVerification(Guid applicationId, bool approve, string? comment = null)
changed.

2023-02-03 12:29 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                         companyUserAssignedRole.UserRole!.Offer!.AppInstances.Select(x => x.IamClient!.ClientClientId)
changed the query to two queries.

2023-02-06 12:40 UTC, ntruchsess approved these changes

2023-02-06 12:43 UTC, merged