feature/cplp-2077-add-agreement-documentId
catenax-ng/tx-portal-backend pull request #147
Opened 2023-02-02 05:17 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-2077

2023-02-02 08:56 UTC, ntruchsess requested changes

2023-02-02 08:56 UTC, ntruchsess commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
now as the link-table AgreementAssignedDocuments has been replaced by a single foreign key DocumentId in Agreement that documentId in the agreement must be set to null.

2023-02-02 08:56 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
> +                agreement.Document!.Id
no need to use the navigational property, just directly use 'agreement.DocumentId'

2023-02-02 08:56 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Agreement.cs
> +    public virtual Document? Document { get; private set; }
as this is not a collection the setter shall be public

2023-02-03 04:15 UTC, qxz2mqe commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
fixed

2023-02-03 04:15 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
> +                agreement.Document!.Id
fixed

2023-02-03 04:15 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Agreement.cs
> +    public virtual Document? Document { get; private set; }
fixed

2023-02-06 08:08 UTC, ntruchsess requested changes

2023-02-06 08:08 UTC, ntruchsess commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +                _logger.LogInformation("Cleaning up {DocumentCount} Documents, {AgreementIdsCount} AgreementAssignedDocuments and {OfferIdCount} OfferAssignedDocuments", documentData.Count, null, doc
logging 'null' is pointless.

2023-02-06 08:08 UTC, ntruchsess commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
cannot see any fix for that. As neither client- nor database-side cascade-delete is active column document_id in table agreements must explicitly set to null whenever the linked row in documents is deleted.

2023-02-07 04:05 UTC, qxz2mqe commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +                _logger.LogInformation("Cleaning up {DocumentCount} Documents, {AgreementIdsCount} AgreementAssignedDocuments and {OfferIdCount} OfferAssignedDocuments", documentData.Count, null, doc
fixed

2023-02-07 04:05 UTC, qxz2mqe commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
fixed

2023-02-07 09:16 UTC, ntruchsess requested changes

2023-02-07 09:16 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreement_assigned_documents.json
> -    "document_id": "00000000-0000-0000-0000-000000000002"
document_ids must be migrated into agreements.json, otherwise this seeding-data is just lost.

2023-02-07 09:16 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Agreement.cs
> +    public Agreement(Guid id, Guid? documentId)
that constructor breaks the seeding. Please remove. Use:
```new Agreement(agreementId, default, null!, default) { DocumentId = data.DocumentId }```
instead

2023-02-07 09:16 UTC, ntruchsess commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
this is how to use AttachRange properly:
```
var agreementsToDeleteDocumentId = documentData.SelectMany(data => data.AgreementIds.Select(agreementId => new Agreement(agreementId, default, null!, default) { DocumentId = data.DocumentId })).ToList();
dbContext.Agreements.AttachRange(agreementsToDeleteDocumentId);
agreementsToDeleteDocumentId.ForEach(agreement => agreement.DocumentId = null);
```

2023-02-07 10:16 UTC, qxz2mqe commented on src/maintenance/Maintenance.App/BatchDeleteService.cs
> +
done

2023-02-07 10:16 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreement_assigned_documents.json
> -    "document_id": "00000000-0000-0000-0000-000000000002"
done

2023-02-07 10:16 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Agreement.cs
> +    public Agreement(Guid id, Guid? documentId)
done

2023-02-07 22:24 UTC, merged