feature/cplp-1834-document-types
catenax-ng/tx-portal-backend pull request #165
Opened 2023-02-10 12:12 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1834

2023-02-10 23:34 UTC, ntruchsess requested changes

2023-02-10 23:34 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Enums/DocumentTypeId.cs
> +    ADDITIONAL_DETAILS = 4,
you cannot just rearrange the enum-values without migrating existing data. Before the change ADDITIONAL_DETAILS was 5, now it is 4, APP_LEAD_IMAGE was 6, now it is 5 etc...
existing records in db refer to enum-values 1,3,4,5,6,7, that means documents that were marked as APP_DATA_DETAILS now seem to be ADDITIONAL_DETAILS, ADDITIONAL_DETAIL-documents now appear as APP_LEAD_IMAGES.
Either the migration must contain code that modifies those entries appropriately (both in up and down) or the value of the deleted enum-member APP_DATA_DETAILS is just skipped while the new members are just added after the old ones (there wouldn't be a member 4 then...). In any case the migration must contain sql-code that removes all obsolete document-data that refers to the to-be-deleted member APP_DATA_DETAILS.

2023-02-13 12:38 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/Enums/DocumentTypeId.cs
> +    ADDITIONAL_DETAILS = 4,
Resolved

2023-02-14 10:49 UTC, ntruchsess requested changes

2023-02-14 10:49 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230213100306_CPLP-1834-AddRemoveDocumentTypeS.cs
> +            migrationBuilder.DeleteData(
as 4 is being re-mapped from APP_DATA_DETAILS to CONFORMITY_APPROVAL_REGISTRATION when going back everything that has been uploaded as CONFORMITY_APPROVAL_REGISTRATION needs to be deleted pretty much the same way as APP_DATA_DETAILS-documents in up().

2023-02-14 10:55 UTC, ntruchsess requested changes
seeding-data contains documents where "document_type_id": 4 is being set. All related records (e.g. offer_assigned_documents) and affected unit-tests need to be adjusted

2023-02-15 05:19 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230213100306_CPLP-1834-AddRemoveDocumentTypeS.cs
> +            migrationBuilder.DeleteData(
fixed

2023-02-15 11:59 UTC, ntruchsess requested changes
As being stated before - seeding data needs to be adjusted as well (documents.consortia.json contains a document referencing document_type_id 4. That entry and anything that creates an fk-reference to it needs to be removed)

2023-02-15 19:28 UTC, ntruchsess approved these changes

2023-02-16 09:54 UTC, merged