feature/cplp-1832-getapplication-companyaddress-refactoring
catenax-ng/tx-portal-backend pull request #18
Opened 2022-12-09 14:52 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1832

2022-12-09 16:56 UTC, ntruchsess requested changes

2022-12-09 16:56 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyWithAddress.cs
> +    public IEnumerable<AgreementsData>? CompanyRoles { get; set; }
This record is shared between the GET and the POST endpoint. As the POST-endpoint neither processes CompanyRoles nor CompanyUsers instead of declaring those IEnumerables as nullable a new record-type shall be created for the GET-endpoint where those IEnumerables are non-nullable.

2022-12-09 16:56 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    CompanyUser = companyApplication.Invitations.Select(x=>new InvitedCompanyUser(x.CompanyUserId,x.CompanyUser!.Firstname!,x.CompanyUser!.Lastname!,x.CompanyUser!.Email!))
FirstName, LastName and Email are nullable in the database. The receiving types properties must be declared as nullable as well. (You cannot transform a null into anything by using the !-operator. That operator just overrides the compiler checking the nullability but doesn't do anything to the real references)

2022-12-09 16:56 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyRoles!.GroupBy(x=>x.CompanyRoleId).Select(g => new AgreementsRoleData(g.Key, g.Select(y=>new Agreements(y.AgreementId,y.ConsentStatusId!)))),
This is improper use of !-operator. if consentstatusid is nullable because the query might actually return a null then the corresponding property in Agreement must be declared as nullable as well.
! may be used in places where a null-check has been done that ensures the reference actually is not null (even if the compiler does'nt know).
! may also be used without such null-check only in expressions that are not executed at runtime but evaluated for other purposes (like the linq-expressions in IQueryable-method arguments that are parsed to to build an sql-query but never get executed at runtime).

2022-12-12 08:47 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyWithAddress.cs
> +    public IEnumerable<AgreementsData>? CompanyRoles { get; set; }
fixed

2022-12-12 08:47 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    CompanyRoles = companyApplication.Company.CompanyAssignedRoles.SelectMany(companyAssignedRole => companyAssignedRole.CompanyRole!.AgreementAssignedCompanyRoles.Select(x => new Agr
fixed

2022-12-12 08:47 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyRoles!.GroupBy(x=>x.CompanyRoleId).Select(g => new AgreementsRoleData(g.Key, g.Select(y=>new Agreements(y.AgreementId,y.ConsentStatusId!)))),
fixed

2022-12-13 07:33 UTC, jjeroch commented
@Phil91 can you please do the re-review of the pr?

2022-12-13 07:50 UTC, Phil91 requested changes
Currently there are no unit tests. PLease add some to get our 80% test coverage goal

2022-12-13 07:50 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    CountryDe = companyApplication.Company.Address.Country!.CountryNameDe,
why are we returning the de name here? Wouldn't it make more sense to return the alpha2code? than the frontend could get the name in the correct language for the user

2022-12-13 07:50 UTC, Phil91 commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    public record CompanyUsers(Guid UserId, string? FirstName, string? LastName, string? Email);
Please change the name since its not a collection of companyUsers - CompanyUserData for example

2022-12-13 07:50 UTC, Phil91 commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    public record Agreements(Guid AgreementId, ConsentStatusId? ConsentStatusId);
Same here, please change the name from Agreements to e.g. AgreementData

2022-12-13 07:50 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyRoles!.GroupBy(x=>x.CompanyRoleId).Select(g => new AgreementsRoleData(g.Key, g.Select(y=>new Agreements(y.AgreementId,y.ConsentStatusId!)))),
isn't fixed in my opinion, we only have a null check for the companyWithAddress object, but there is no check on CompanyRoles, the ConsentStatusIds and the CompanyUser including the first, lastname and email. Please add null checks or make the properties in the return type nullable. If for some reason we have a data inconsistency we'd get an unhandled exception here

2022-12-13 10:20 UTC, ntruchsess requested changes

2022-12-13 10:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> -/********************************************************************************
please revert all those whitespace-changes caused by having changed the linebreaks from unix to windows style. (use e.g. dos2unix to convert back).

2022-12-13 10:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyWithAddress.cs
> -/********************************************************************************
please revert all those whitespace-changes caused by having changed the linebreaks from unix to windows style. (use e.g. dos2unix to convert back).

2022-12-13 10:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    companyApplication.Invitations.Select(x=>new InvitedCompanyUser(x.CompanyUserId,x.CompanyUser!.Firstname!,x.CompanyUser!.Lastname!,x.CompanyUser!.Email!)))
please fix the !-operators. e.g. InvitedCompanyUser.Email is declared as nullable, therefore the last ! in x.CompanyUser!.Email! is redundant.

2022-12-13 10:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserRoleWithAddress.cs
> +    IEnumerable<AgreementsData> CompanyRoles,
the names of properties CompanyRoles and CompanyUser are misleading as there are entity-type of the same name. Rather use e.g. 'AgreementDatas' and 'InvitedUsers'

2022-12-19 17:42 UTC, ntruchsess requested changes

2022-12-19 17:42 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyRoles!.GroupBy(x => x.CompanyRoleId).Select(g => new AgreementsRoleData(g.Key, g.Select(y => new AgreementConsentData(y.AgreementId, y.ConsentStatusId)))),
please remove the redundant !-operator: CompanyRoles is not nullable.
please rename 'CompanyRoles' as it doesn't refert to the type CompanyRole but AgreementData, this is misleading.

2022-12-19 17:42 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyUser!.Select(x => new InvitedCompanyUserData(x.UserId, x.FirstName, x.LastName, x.Email))
please remove the redundant !-operator: CompanyUser is not nullable.
please rename 'CompanyUser' as it doesn't refert to the type CompanyUser but InvitedCompanyUser, this is misleading. E.g. 'InvitedUserData' would be appropriate. Also rename the type InvitedCompanyUser to something like CompanyUserData (as it doesn't refer to CompanyUser but only a subset of it's properties)

2022-12-19 17:42 UTC, ntruchsess commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    IEnumerable<AgreementsRoleData>? CompanyRoles,
please rename appropriately. 'CompanyRoles' would refer to the entity-type which is misleading

2022-12-19 17:42 UTC, ntruchsess commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    IEnumerable<InvitedCompanyUserData>? CompanyUser
please rename appropriately. CompanyUser is misleading as it does not refer to the entity-type (but to a type that has only a subset of it's properties).

2022-12-19 17:42 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTest.cs
> +        results.Should().NotBeNull();
there should be more asserts testing the expected result:
The seeding-data should contain appropriate data for properties AgreementsData and InvitedCompanyUser (bolth data that is expected to be selected plus data that is expected not(!) to be selected). Then the assert in this test should verify the query does return only the selected data.

2022-12-19 17:42 UTC, ntruchsess commented on tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
> +
please revert this redundant whitespace change.

2022-12-20 06:32 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            companyWithAddress.CompanyUser!.Select(x => new InvitedCompanyUserData(x.UserId, x.FirstName, x.LastName, x.Email))
CompanyUserData is already defined in namespace so it gives ambiguous reference. I have renamed it to InvitedUserData

2022-12-20 06:33 UTC, qxz2mqe commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    IEnumerable<AgreementsRoleData>? CompanyRoles,
fixed

2022-12-20 06:33 UTC, qxz2mqe commented on src/administration/Administration.Service/Models/CompanyWithAddressData.cs
> +    IEnumerable<InvitedCompanyUserData>? CompanyUser
fixed

2022-12-20 06:33 UTC, qxz2mqe commented on tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
> +
fixed

2022-12-21 09:08 UTC, qxz2mqe commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTest.cs
> +        results.Should().NotBeNull();
fixed

2023-01-10 15:50 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyWithAddress.cs
> -/********************************************************************************
that should have been an easy task - why has this been ignored for weeks now?

2023-01-10 15:50 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> -/********************************************************************************
that should have been an easy task - why has this been ignored for weeks now? As it was causing massive conflicts on whole file when merging main I did fix it.

2023-01-10 15:51 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    CountryDe = companyApplication.Company.Address.Country!.CountryNameDe,
I did discuss with @jjeroch , we will remove with future ticket

2023-01-10 15:55 UTC, ntruchsess approved these changes
I did fix all remaining issues and improved the unit-tests

2023-01-10 15:56 UTC, merged