feat(autosetup)!: Refactor autosetup process
catenax-ng/tx-portal-backend pull request #204
Opened 2023-02-21 15:55 UTC by Phil91

The autosetup process is changed for offers of type Service For ServiceType DATASPACE_SERVICE only the subscription record and if set a technical user is created For ServiceType CONSULTANCE_SERVICE only the subscription record is created

Refs: CPLP-1845

2023-03-01 19:58 UTC, ntruchsess requested changes
I did minor cleanup - please pull before working on the comments

2023-03-01 19:58 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +            var (clientId, iamClientId) = await CreateClient(data, userRolesRepository, offerDetails);
consider validation of data.OfferUrl to be wellformed ( I suggest use of https://github.com/catenax-ng/tx-portal-backend/blob/705cedf1b8b2a97441e89bc71abf8eac1927e137/src/framework/Framework.IO/UrlHelper.cs#L30 )

2023-03-01 19:58 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +        var redirectUrl = data.OfferUrl.EndsWith("/") ? $"{data.OfferUrl}*" : $"{data.OfferUrl}/*";
I suggest to use the existing framework-method to append to path: https://github.com/catenax-ng/tx-portal-backend/blob/705cedf1b8b2a97441e89bc71abf8eac1927e137/src/framework/Framework.IO/UrlHelper.cs#L56

2023-03-01 19:58 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/ServiceDetail.cs
> +    public bool TechnicalUserNeeded { get; private set; }
shouldn't this be settable to support later update? We only define columns as private set if there is a good reason (like a foreign key for a relationship that must never change (e.g. ServiceDetails being a Service-specific extension of Offer for a specific service) will never be reassigned to a different offer)

2023-03-01 19:58 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +                .WithMany(e => e.ServiceDetails)
is this really 1-N? Shall a specific Service really have multiple sets of service-specific properties assigned? (like can a service belong to multiple ServiceTypes? and if so does the same apply to all other detail properties like the requirement to create a technical user?)

2023-03-01 19:58 UTC, ntruchsess commented on src/provisioning/Provisioning.Library/Extensions/ServiceAccountManager.cs
> +        return ($"{_Settings.ServiceAccountClientPrefix}{id}", id.ToString());
As there is only a single reference to this method consider relocating the complete method from ProvisioningManager into ServiceAccountCreation-service.

2023-03-02 07:56 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +            var (clientId, iamClientId) = await CreateClient(data, userRolesRepository, offerDetails);
check added

2023-03-02 07:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +                .WithMany(e => e.ServiceDetails)
yes, it's possible that one service has multiple ServiceTypes and e.g. only one of them has a technical user

2023-03-02 07:57 UTC, Phil91 commented on src/provisioning/Provisioning.Library/Extensions/ServiceAccountManager.cs
> +        return ($"{_Settings.ServiceAccountClientPrefix}{id}", id.ToString());
moved to ServiceAccountCreationService

2023-03-02 07:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/ServiceDetail.cs
> +    public bool TechnicalUserNeeded { get; private set; }
absolutely right, removed the private of the setter

2023-03-02 07:57 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +        var redirectUrl = data.OfferUrl.EndsWith("/") ? $"{data.OfferUrl}*" : $"{data.OfferUrl}/*";
good advice. adjusted

2023-03-02 07:57 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +            var response = await httpClient.PostAsJsonAsync(autoSetupUrl, autoSetupData).ConfigureAwait(false);
good advice. adjusted

2023-03-02 09:41 UTC, ntruchsess approved these changes

2023-03-02 09:51 UTC, merged