feature/cplp-2235-conformity-document-type-app-api
catenax-ng/tx-portal-backend pull request #222
Opened 2023-02-27 06:35 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-2235

2023-03-02 13:36 UTC, Phil91 requested changes
Please add a PR for the config changes in the CD repository as well

2023-03-02 13:36 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            throw new ConflictException($"invalid DocumenType: [{String.Join(", ", invalidDocumentType)}]");
The implementation currently deviates from the described behavior in the task.

At the moment it is checked if other DocumentTypeIds are uploaded as well, the check has to be adapted.

It should be checked whether specifically all of the three "Conformity_Approval_Business_Apps", "APP_LEADIMAGE", "APP_IMAGE" have been uploaded. If this is not the case, different error messages should be returned.

2023-03-03 11:03 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            throw new ConflictException($"invalid DocumenType: [{String.Join(", ", invalidDocumentType)}]");
fixed

2023-03-03 11:34 UTC, Phil91 requested changes

2023-03-03 11:34 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +        var isvalidDocumentType = offerDetails.DocumentTypeIds.All(x=>submitAppDocumentTypeIds.Contains(x));
please change to `submitAppDocumentTypeIds.All(x=> offerDetails.DocumentTypeIds.Contains(x))`

2023-03-03 11:34 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            throw new ConflictException($"Conformity_Approval_Business_Apps,  APP_LEADIMAGE, APP_IMAGE are mandatory document type");
Please change to `$"{string.Join(",", submitAppDocumentTypeIds)} are mandatory document types`

2023-03-03 11:34 UTC, Phil91 commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
> +        result.Message.Should().StartWith($"Conformity_Approval_Business_Apps,  APP_LEADIMAGE, APP_IMAGE are mandatory document type");
Please adjust the error message to only contain the values which are provided within the parameters

2023-03-03 13:06 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            throw new ConflictException($"Conformity_Approval_Business_Apps,  APP_LEADIMAGE, APP_IMAGE are mandatory document type");
Fixed

2023-03-03 13:06 UTC, qxz2mqe commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
> +        result.Message.Should().StartWith($"Conformity_Approval_Business_Apps,  APP_LEADIMAGE, APP_IMAGE are mandatory document type");
fixed

2023-03-03 13:06 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            throw new ConflictException($"invalid DocumenType: [{String.Join(", ", invalidDocumentType)}]");
fixed

2023-03-03 13:08 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +        var isvalidDocumentType = offerDetails.DocumentTypeIds.All(x=>submitAppDocumentTypeIds.Contains(x));
I tried to implement in this way as you suggested here but it is giving wrong result. Please verify it. I tested in postman and the way i implemented giving expected output

2023-03-03 14:26 UTC, Phil91 requested changes

2023-03-03 14:26 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +        var isvalidDocumentType = offerDetails.DocumentTypeIds.All(x=>submitAppDocumentTypeIds.Contains(x));
just checked it. for example add DocumentTypeId.APP_CONTRACT in line 671 in the OfferServiceTests, the test will fail with the current implementation.

But it is allowed that more than the documentTypeIds of the settings are uploaded. But those configured must be uploaded

2023-03-06 16:47 UTC, Phil91 approved these changes

2023-03-07 07:15 UTC, merged