change (emailTemplate): update content next steps
catenax-ng/tx-portal-backend pull request #226
Opened 2023-02-28 12:45 UTC by jjeroch

Email Template "Next Steps" html updated.
- "quick links" deleted since they are not necessary/needed for this email template
- padding updated

2023-03-02 12:33 UTC, Phil91 requested changes

2023-03-02 12:33 UTC, Phil91 commented on src/mailing/Mailing.Template/EmailTemplates/nextsteps.html
> +              <td align="left" style="padding:0;Margin:0;padding-top:0px;padding-left:20px;padding-right:20px">
i'd suggest removing the padding-left & right as well.

without padding:
![image](https://user-images.githubusercontent.com/7672600/222429751-52276135-326e-459c-b936-160b1a41eb54.png)

with padding:
![image](https://user-images.githubusercontent.com/7672600/222429895-1d5a5786-fea3-4dc3-91a9-054c8b1ac6c4.png)

in my opinion the footer looks better without padding.

2023-03-02 19:56 UTC, jjeroch commented on src/mailing/Mailing.Template/EmailTemplates/nextsteps.html
> +              <td align="left" style="padding:0;Margin:0;padding-top:0px;padding-left:20px;padding-right:20px">
agree kicking it out

2023-03-02 20:01 UTC, jjeroch commented
@Phil91 I decided to get ride of even more - can you regenerate the email once again to have a quick look if it still looks good

2023-03-03 06:58 UTC, Phil91 approved these changes

2023-03-12 22:18 UTC, merged