feat(app): introduce single instance app
catenax-ng/tx-portal-backend pull request #252
Opened 2023-03-10 18:08 UTC by Phil91

add endpoint to add app instance information
edit activate app process
edit offer subscription process for single instance apps

Refs: CPLP-1846

2023-03-27 20:36 UTC, ntruchsess requested changes
I did some minor cleanup and rebased on dev resolving the conflicts that resulted from the merge or Majids PR. Please make sure to get those changes before proceeding

2023-03-27 20:36 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/AppInstanceSetup.cs
> +    public virtual IamServiceAccount? ServiceAccount { get; private set; }
From my point of view this should rather link the companyServiceAccount not the iamServiceAccount (iamService-account is designed being a pure link in between companyServiceAccount and keycloak)
I'm also not sure whether the AppInstanceSetup entity should link the technical user at all. Isn't appInstanceSetup a container that defines this app should be set up as singleinstance app so it contains all data that is required to do so? From my point of view the technical user is the result of this setup and should be linked to the actual app-instance not the setup-data.

2023-03-28 07:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                Company = o.ProviderCompany, OfferId = o.Id, OfferName = o.Name,
absolutely right, removed it.

2023-03-28 07:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/IamClient.cs
> +    public bool Disabled { get; set; }
removed from the database

2023-03-28 07:44 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/AppInstanceSetup.cs
> +    public virtual IamServiceAccount? ServiceAccount { get; private set; }
changed it to companyServiceAccount and moved it to the `AppInstance`

2023-03-29 06:25 UTC, Phil91 commented
@ntruchsess did the change regarding the technical user profile. it's ready to be reviewed again

2023-03-29 21:16 UTC, ntruchsess requested changes
I did some cleanup rebasing on latest dev. Please make sure to get those updates before proceeding.

2023-03-29 21:16 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +    public async Task SetupSingleInstance(Guid offerId, string instanceUrl)
that method should validate there is no preexisting appinstance before creating a new one.

2023-03-30 06:01 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +    public async Task SetupSingleInstance(Guid offerId, string instanceUrl)
valid point 👍  added

2023-03-30 06:01 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +        await _provisioningManager.DeleteCentralClientAsync(clientClientId)
At this point there shouldn't be any technical users assigned to the app instance (at least process wise that's not possible). If added the delete for it anyway.
In my point of view, we should somehow add a generic logic for our keycloak calls where we could do rollbacks if failing

2023-03-30 10:01 UTC, ntruchsess requested changes

2023-03-30 10:43 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +                sa => { sa.OfferSubscriptionId = subscriptionId; })
added the coverage for that

2023-03-30 12:13 UTC, ntruchsess commented
lgtm. Will approve as soon it is rebased and has the Migration recreated after merge of https://github.com/catenax-ng/tx-portal-backend/pull/301

2023-03-30 13:21 UTC, Phil91 commented
> lgtm. Will approve as soon it is - after merge of #301 - rebased and has the Migration recreated

will do the migration recreation 👍

2023-03-30 13:29 UTC, ntruchsess approved these changes
did rebase and recreate the migration

2023-03-30 13:38 UTC, merged