feat(serviceRelease): get service type
catenax-ng/tx-portal-backend pull request #253
Opened 2023-03-13 07:10 UTC by qxz2mqe

added new endpoint to get service type data
Refs: CPLP-2347

2023-03-13 08:57 UTC, Phil91 requested changes

2023-03-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/ServiceTypeData.cs
> +public record ServiceTypeData(int ServiceTypeId, string Name);
ServiceTypeId need to be of ServiceTypeId

2023-03-13 08:57 UTC, Phil91 commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> +
Please remove empty line

2023-03-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.ServiceDetails.Select(x => x.ServiceTypeId),
In the task it looks like we should return the label of ServiceType here

2023-03-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +            .Select(serviceType => new ServiceTypeData((int)serviceType.Id, serviceType.Label))
the first parameter of ServiceTypeData should be the enum value, in my understanding of type ServiceTypeId

2023-03-13 08:57 UTC, Phil91 commented on tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
> +    public async Task GetServiceDetailsByIdAsync_WithInvalidOfferStatus_ThrowsException()
Please add a test for the no service existing case as well

2023-03-13 15:50 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.ServiceDetails.Select(x => x.ServiceTypeId),
fixed

2023-03-13 15:50 UTC, qxz2mqe commented on tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
> +    public async Task GetServiceDetailsByIdAsync_WithInvalidOfferStatus_ThrowsException()
fixed

2023-03-14 07:57 UTC, Phil91 approved these changes

2023-03-14 07:58 UTC, merged