feature/CPLP-1829-submitregistration refactoring
catenax-ng/tx-portal-backend pull request #26
Opened 2022-12-15 13:01 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1829

2022-12-27 05:43 UTC, qxz2mqe reviewed
Please check my review comments

2022-12-28 05:42 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        else
This else condition for validation is not require otherwise it will break whole flow. if there is no document other flow should executed normally

2022-12-28 05:43 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationUserEmailData.cs
> +public record CompanyApplicationUserEmailData(CompanyApplicationStatusId CompanyApplicationStatusId, Guid CompanyUserId, string? Email, IEnumerable<DocumentStatusData>? DocumentDatas);
change IEnumerable<DocumentStatusData>?  nullable to IEnumerable<DocumentStatusData> not nullable

2023-01-02 08:33 UTC, Phil91 requested changes

2023-01-02 08:33 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationUserEmailData.cs
> +
Please remove linebreaks

2023-01-02 08:33 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +    public void AttachandModifyDocuments(Guid documnetId, Action<Document> setOptionalParameters)
Please change to AttachAndModifyDocument

2023-01-02 08:33 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
>              .SingleOrDefaultAsync();
Please add a linebreak

2023-01-02 08:33 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +
Please remove the linebreak

2023-01-02 08:33 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        }
Please add a linebreak

2023-01-02 08:33 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    documentRepository.AttachandModifyDocuments(document.documentId, doc =>
Please remove the linebreak

2023-01-02 08:33 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                if(document.StatusId != DocumentStatusId.LOCKED)
to reduce the size of the database query only the documents with status != LOCKED can be queried, thus the if can be removed

2023-01-02 08:33 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                Documents = application.Company!.CompanyUsers.SelectMany(companyUser => companyUser.Documents)
can be changed to something like: `Documents = application.Company!.CompanyUsers.SelectMany(companyUser => companyUser.Documents).Where(doc => doc.StatusId != DocumentStatusId.LOCKED)` to optimize the database query

2023-01-03 07:12 UTC, Phil91 requested changes
Smaller formatting issues, also please have a look at the code smell

2023-01-03 07:12 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetails.cs
>  namespace Org.Eclipse.TractusX.Portal.Backend.PortalBackend.DBAccess.Models;
Readd the linebreak

2023-01-03 07:12 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (applicationUserData.DocumentDatas.Any())
Please add the linebreak

2023-01-03 07:12 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                documentRepository.AttachAndModifyDocument(document.documentId, doc =>
Please remove the linebreak

2023-01-03 07:12 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +
Please remove the whitespaces

2023-01-03 10:50 UTC, Phil91 approved these changes

2023-01-03 11:15 UTC, merged