feat(registration): get registration document
catenax-ng/tx-portal-backend pull request #260
Opened 2023-03-16 05:55 UTC by qxz2mqe

added new endpoint to get registration document of CX_FRAME_CONTRACT documenttypeid
Refs: CPLP-2341

2023-03-16 07:43 UTC, Phil91 commented
corresponding CD - [PR](https://github.com/catenax-ng/tx-portal-cd/pull/47) is created

2023-03-20 07:47 UTC, Phil91 requested changes

2023-03-20 07:47 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var documentDetails = await documentRepository.GetDocumentAsync(documentId, _settings.RegistrationDocumentTypeIds).ConfigureAwait(false);
documentDetails could be `default` here which would mean no document for the given id was found, please add a check for that.
Please add a unitTests for that as well

2023-03-20 09:45 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var documentDetails = await documentRepository.GetDocumentAsync(documentId, _settings.RegistrationDocumentTypeIds).ConfigureAwait(false);
fixed

2023-03-21 08:27 UTC, Phil91 approved these changes

2023-03-21 08:32 UTC, merged