bug(appchange): get app description
catenax-ng/tx-portal-backend pull request #278
Opened 2023-03-23 04:40 UTC by qxz2mqe

moving end point app description from app to app change controller
ref:-CPLP-2345

2023-03-24 07:01 UTC, Phil91 requested changes

2023-03-24 07:01 UTC, Phil91 commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> -        await this.WithIamUserId(userId => _appsBusinessLogic.GetAppUpdateDescriptionByIdAsync(appId, userId)).ConfigureAwait(false);
Github does not let me make a comment where i want to. But regarding to the ticket description the method CreateOrUpdateAppDescriptionsByIdAsync should've been moved to the AppChangeController as well. Please make sure to do so

2023-03-28 11:05 UTC, qxz2mqe commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> -        await this.WithIamUserId(userId => _appsBusinessLogic.GetAppUpdateDescriptionByIdAsync(appId, userId)).ConfigureAwait(false);
fixed

2023-03-31 05:35 UTC, Phil91 submitted a review, later dismissed

2023-04-05 20:10 UTC, Phil91 approved these changes

2023-04-05 20:23 UTC, merged