Defect/CPLP-1944-Email-Key-Value-Missing
catenax-ng/tx-portal-backend pull request #28
Opened 2022-12-16 08:59 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1944

2022-12-19 16:50 UTC, ntruchsess requested changes

2022-12-19 16:50 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +                { "offerProviderName", string.Concat(FirstName, LastName)??"Service Manager" },
string.Concat will do the same as operator +. There will be no separating space in between FirstName and LastName which will look rather odd. In addition to that the result of string.concat is never null as it uses String.Empty for any null value and would return string.empty if both arguments are null. Please add a private method similar to https://github.com/catenax-ng/tx-portal-backend/blob/a2b9277b48d403c69db9ec728043236bdfc92081/src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs#L202 to build a suitable name-string

2022-12-19 16:50 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Select(x => new ValueTuple<string, string, string>(x.Email!, x.Firstname!, x.Lastname!))
the !-operators are incorrect, you have to declare the returntype with nullable elements like so:
```(string? Email, string? FirstName, string? LastName)```

2022-12-20 04:29 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +                { "offerProviderName", string.Concat(FirstName, LastName)??"Service Manager" },
fixed

2022-12-20 04:30 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Select(x => new ValueTuple<string, string, string>(x.Email!, x.Firstname!, x.Lastname!))
fixed

2022-12-27 11:04 UTC, jjeroch commented
2 PRs for the same ticket? 
https://github.com/catenax-ng/tx-portal-backend/pull/25

2023-01-02 08:38 UTC, Phil91 requested changes

2023-01-02 08:38 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +                { "offerProviderName", CreateNameString(FirstName, LastName)},
`CreateNameString(FirstName, LastName)` can be shortend to something like: `var userName = string.Join(" ", new[] { receiver.Name, receiver.LastName }.Where(item => !string.IsNullOrWhiteSpace(item)));` than the assignement here would be `!string.IsNullOrWhiteSpace(userName) ? userName : "Service Manager"`

2023-01-10 16:11 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +                { "offerProviderName", CreateNameString(FirstName, LastName)},
I like this recommendation :-)

2023-01-10 16:28 UTC, ntruchsess approved these changes

2023-01-10 16:29 UTC, merged