feat(servicerelease):get offer(services) in_review and active state
catenax-ng/tx-portal-backend pull request #280
Opened 2023-03-23 10:02 UTC by qxz2mqe

New Endpoint to Get all services in status "in Review" & "ACTIVE" 
ref:- CPLP-2417

2023-03-24 06:56 UTC, Phil91 requested changes

2023-03-24 06:56 UTC, Phil91 commented on src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
> +    [Authorize(Roles = "approve_service_release,decline_service_release")]
@jjeroch do we want to go with the check for both roles or would it be better to have a combined role for this?

2023-03-24 06:56 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
> +        result!.Data.Should().HaveCount(3);
we could check if the sorting is correct here

2023-03-24 06:56 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
> +    [InlineData(new[] { OfferStatusId.ACTIVE }, OfferSorting.NameDesc,null,"en")]
since you're using only one inlineData the test could be a Fact instead of theory. Alternativly please add a few more inlineData to have multiple runs with different parameters

2023-03-24 11:11 UTC, jjeroch commented on src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
> +    [Authorize(Roles = "approve_service_release,decline_service_release")]
to keep it simple (regarding the change) I would go for two roles still. Reason: the change would impact the R&R concept, keycloak image, the app endpoint and this endpoint and the documentation. I dont see an issue to improve this in future but would prefer to do this afterwards and not anymore in this release

2023-03-28 12:06 UTC, jjeroch commented
@qxz2mqe can we get this ready for a new review by Philip and Norbert tomorrow before lunch?

2023-03-28 21:01 UTC, Phil91 approved these changes

2023-03-29 05:28 UTC, qxz2mqe commented
> @jjeroch It is ready for review and philip has reviewed and approved it

2023-03-29 11:49 UTC, jjeroch commented
> > @jjeroch It is ready for review and philip has reviewed and approved it

@qxz2mqe alright can you have a look into the conflicts as soon as you have finished the work on the /provided endpoint, ideally afterwards we can merge it

2023-03-29 23:29 UTC, ntruchsess approved these changes

2023-03-29 23:29 UTC, merged