feature/CPLP-1528-CPLP-1529-companyroleConsentDetails
catenax-ng/tx-portal-backend pull request #288
Opened 2023-03-27 06:11 UTC by VPrasannaK94

chore: fixing logic for Get and Post companyRoleConsentDetails

Ref: CPLP-1528,CPLP-1529

2023-03-29 00:45 UTC, ntruchsess commented
@VPrasannaK94 : I did some cleanup, and as there were conflicts I also rebased on dev solving the conflicts. Please make sure you get those changes in case you need to add anything to the PR.

2023-03-29 07:24 UTC, ntruchsess requested changes
in addition to my comments we need to clarify a semantic detail - what if agreements where there is already an active consent for in the database are not included in the request: shall those consents be set to inactive or just be ignored?

2023-03-29 07:24 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            if(!result.AgreementAssignedRoles.Contains(data.CompanyRole) || data.Agreements.Any(x => x.ConsentStatus != ConsentStatusId.ACTIVE))
this check is not sufficient to validate the request-data in terms of completeness of signed consents. you need to read all agreements that are required to get signed for a company-role from the database and validate whether all those required agreements are actually singed. the current implementation only validates the agreements that are actually send by the frontend. If an agreement is completely missing here the existing check wouldn't notice

2023-03-29 07:24 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            foreach(var agreementData in data.Agreements)
I prepered a method AddAttachAndModifyConsents in consent-repo to update the agreements more efficiently. A call to that method would replace most of lines 115-140 in src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs

2023-03-30 18:13 UTC, VPrasannaK94 commented
> in addition to my comments we need to clarify a semantic detail - what if agreements where there is already an active consent for in the database are not included in the request: shall those consents be set to inactive or just be ignored?

I discussed this scenario with @jjeroch  , asked me to ignore when consent record with active status.

2023-03-30 21:29 UTC, ntruchsess requested changes
I did a complete refactoring of CreateCompanyRoleAndConsentAgreementDetailsAsync, please check this out to learn how to use linq efficiently instead of iterating + processing items in loops. It now does the update only if all preconditions are satisfied.
Please make sure to pull before working on my comments regarding CPLP-1528.

2023-03-31 09:58 UTC, VPrasannaK94 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                x.CompanyRole.CompanyRoleRegistrationData!.IsRegistrationRole,
As myself and @jjeroch discussed about companyRoleActive and she said it okay to take it from IsRegistrationRole. 

and Asked if there is any better approach to implement  companyRoleActive status then the current implementation, Please guide me so that ,I can implement it.

2023-04-01 19:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                x.CompanyRole.CompanyRoleRegistrationData!.IsRegistrationRole,
companyroles just don't have a status, so there is no 'active/inactive'. IsRegistrationRole is there to define which roles are to be choosen from in registration process. (a company shall not be able to apply for CompanyRoleId.OPERATOR).
There is also no status in CompanyAssignedRole. A role can be either assigned or not assigned.
@jjeroch : The question is what is the frontend going to do with 'CompanyRoleActive'?

2023-04-03 19:52 UTC, jjeroch commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                x.CompanyRole.CompanyRoleRegistrationData!.IsRegistrationRole,
@ntruchsess Prasanna and I synced on the endpoint and there is a misunderstanding in the implementation. New code will get submitted this week

2023-04-03 19:52 UTC, jjeroch commented
@VPrasannaK94 since you are working on the pr currently, I suggest we put this PR into the draft mode

2023-04-11 21:55 UTC, ntruchsess approved these changes
did fix my review comments reworking the response-format to include all agreements including those that do not (yet) have a consent created for.

2023-04-11 21:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +            .Where(companyRole => companyRole.CompanyRoleRegistrationData!.IsRegistrationRole == true)
fixed

2023-04-11 21:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                    .Where(assigned => assigned.Agreement!.IssuerCompanyId == x.CompanyId)
fixed

2023-04-11 21:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                x.CompanyRole.CompanyRoleRegistrationData!.IsRegistrationRole,
did rework as discussed. Get endpoint response now contains all agreements (including those that do not have a consent yet)

2023-04-11 21:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyRole.cs
> +    public virtual ICollection<CompanyAssignedRole> CompanyAssignedRole { get; private set; }
fixed

2023-04-11 21:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                companyRole.CompanyAssignedRole.Where(x => x.CompanyId == companyId).Any( roleId => roleId.CompanyRoleId == companyRole.Id),
fixed

2023-04-13 08:31 UTC, ntruchsess approved these changes

2023-04-13 08:40 UTC, merged