feature/cplp-1928-api-apps-business-refactor
catenax-ng/tx-portal-backend pull request #31
Opened 2022-12-20 06:52 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1928

2022-12-21 10:00 UTC, Phil91 requested changes

2022-12-21 10:00 UTC, Phil91 commented on src/marketplace/Offers.Library/Models/BusinessAppData.cs
> +public record BusinessAppData(Guid Id, string Name, string Uri, IEnumerable<Guid> LeadPictureIds, string Provider);
As described in the user story, only a single value should get returned.

2022-12-21 10:00 UTC, Phil91 commented on src/marketplace/Offers.Library/Models/BusinessAppData.cs
> +public record BusinessAppData(Guid Id, string Name, string Uri, IEnumerable<Guid> LeadPictureIds, string Provider);
The name can be changed to 'LeadPictureId' than

2022-12-21 10:00 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                    x.LeadPictureIds,
Since we should only return one document id, a check should be added to check if there are multiple documents matching the query, if so a ConflictException should be thrown

2022-12-21 10:04 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Models/BusinessAppData.cs
> +public record BusinessAppData(Guid Id, string Name, string Uri, IEnumerable<Guid> LeadPictureIds, string Provider);
I dont think so Same logic applied for CPLP-1927.Please have a look Norbert has reviewed and commented
https://github.com/catenax-ng/tx-portal-backend/pull/30#pullrequestreview-1223249595

2022-12-21 10:05 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                    x.LeadPictureIds,
Please have a look for Norbert Comments
https://github.com/catenax-ng/tx-portal-backend/pull/30#pullrequestreview-1223249595
All the CPLP-1927,1928,1929,1930 and 1881 has same implementation

2022-12-21 10:08 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                    x.LeadPictureIds,
okay, but in the user story e.g. 1928 last sentence it says:

_and respond with the document id (single respond; no multiple values expected)_

so we should remove the innumerable and change it to GUID

2023-01-02 10:53 UTC, Phil91 approved these changes

2023-01-02 14:19 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                    x.LeadPictureIds,
fixed

2023-01-03 06:49 UTC, merged