feat(apprelease and services):- Post createapp and addservice
catenax-ng/tx-portal-backend pull request #316
Opened 2023-04-07 11:30 UTC by qxz2mqe

added LicenseTypeId for createapp and addservice endpoint
POST: /api/apps/appreleaseprocess/createapp
POST: /api/services/addservice

ref:-CPLP-2491

2023-04-11 07:46 UTC, Phil91 requested changes

2023-04-11 07:46 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230406095655_CPLP-2489-AddLicenseType.cs
> +            migrationBuilder.DropTable(
This drop statement should not be here. We need to keep the old audit table to ensure that we have the old audit data. Please see my comment in `PortalDbContext` and recreate the migration

2023-04-11 07:46 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +    public virtual DbSet<AuditOffer20230406> AuditOffer20230406 { get; set; } = default!;
The old db sets needs to be kept as well. Otherwise this will result in a drop table for the existing audit table which should not happen

```suggestion
    public virtual DbSet<AuditOffer20230119> AuditOffer20230119 { get; set; } = default!;
    public virtual DbSet<AuditOffer20230406> AuditOffer20230406 { get; set; } = default!;
```

2023-04-12 05:02 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +    public virtual DbSet<AuditOffer20230406> AuditOffer20230406 { get; set; } = default!;
fixed

2023-04-12 07:27 UTC, Phil91 approved these changes

2023-04-12 07:31 UTC, merged