fix(notification): create only one notification per user
catenax-ng/tx-portal-backend pull request #321
Opened 2023-04-13 09:11 UTC by Phil91

the notifications will only be created once per request for each user and type

Refs: CPLP-2526

2023-04-13 21:12 UTC, ntruchsess requested changes

2023-04-13 21:12 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            if (!offerProviderDetails.SalesManagerId.HasValue || receiver != offerProviderDetails.SalesManagerId.Value)
I'm pretty sure the second condition is incorrect. As a first notification for the salesmanager is being created in line 244 to skip the creation of a second notification for the same salesManager it must be 'receiver **==** offerProvierDetails.SalesManagerId.Value'.

2023-04-13 21:12 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        await _notificationService.CreateNotifications(_settings.CompanyAdminRoles, null, notifications, companyId).ToListAsync().ConfigureAwait(false);
the respective test (ApplicationActivationTests.cs) needs to be adjusted as well. It contains a fake implementation using 'Invoke', while it should call ReturnsLazily returning IAsnycEnumerable.

2023-04-13 21:12 UTC, ntruchsess commented on src/notifications/Notifications.Library/NotificationService.cs
> +            yield return receiver;
The unit-tests somehow should not just test that the CreateNotifications-method is being called, but also test that the IAsyncEnumerable which is being returned is a actually being iterated.

2023-04-14 07:24 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            if (!offerProviderDetails.SalesManagerId.HasValue || receiver != offerProviderDetails.SalesManagerId.Value)
absolutly right. i've corrected the check and extended the unit tests for it.

2023-04-14 07:24 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        await _notificationService.CreateNotifications(_settings.CompanyAdminRoles, null, notifications, companyId).ToListAsync().ConfigureAwait(false);
added the return to the unitTest

2023-04-14 17:13 UTC, ntruchsess approved these changes

2023-04-14 17:15 UTC, merged