feature/cplp-1930-api-appreleaseprocess-appid-appstatus-refactor
catenax-ng/tx-portal-backend pull request #34
Opened 2022-12-21 04:29 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1930

2022-12-21 10:06 UTC, Phil91 requested changes

2022-12-21 10:06 UTC, Phil91 commented on src/marketplace/Offers.Library/Models/OfferProviderResponse.cs
> +    IEnumerable<Guid> LeadPictureIds,
Same as in #31 & #33 please add a check for multiple items and if there are multiple throw a conflictException. Also rename to LeadPictureId

2022-12-21 10:07 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Models/OfferProviderResponse.cs
> +    IEnumerable<Guid> LeadPictureIds,
Please have a look for Norbert Comments
https://github.com/catenax-ng/tx-portal-backend/pull/30#pullrequestreview-1223249595
All the CPLP-1927,1928,1929,1930 and 1881 has same implementation

2022-12-27 09:40 UTC, jjeroch commented
Multiple document IDs are not needed; we only support single leadImage

2023-01-02 12:29 UTC, Phil91 approved these changes

2023-01-02 12:29 UTC, merged