feat: refactoring inReview endpoints for Apps and Service
catenax-ng/tx-portal-backend pull request #340
Opened 2023-04-20 13:26 UTC by VPrasannaK94

feat: refactoring inReview endpoints for Apps and Service

Ref: CPLP-2504

2023-04-24 06:37 UTC, Phil91 commented
@VPrasannaK94 Please adjust the PR name, you can take the top line of the description

2023-04-24 06:42 UTC, Phil91 requested changes
I've added a question for @jjeroch in the [Ticket](https://jira.catena-x.net/browse/CPLP-2504) we should clarify that before merging

2023-04-24 06:42 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
>      public Task<InReviewOfferData?> GetInReviewAppDataByIdAsync(Guid id, OfferTypeId offerTypeId) =>
Would like to see some unit tests for the changed logic

2023-04-24 06:42 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
>      public Task<ServiceDetailsData?> GetServiceDetailsByIdAsync(Guid serviceId) =>
Would like to see some unit tests for the changed logic

2023-04-27 06:09 UTC, Phil91 approved these changes

2023-04-28 06:47 UTC, ntruchsess requested changes

2023-04-28 06:47 UTC, ntruchsess commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> -        if (result.OfferStatusId != OfferStatusId.IN_REVIEW)
now that OfferStatusId is not being read by non-testing-code any more it should either be removed from ServiceDetailData or be forwarded to the FE by adding it to ServiceData (as OfferStatusId can be either IN_REVIEW or ACTIVE now it would be worth to display it in FE) @jjeroch : please clarify

2023-04-28 06:55 UTC, ntruchsess commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> -        if (result.OfferStatusId != OfferStatusId.IN_REVIEW)
just see that this question has already been answered in CPLP-2504

2023-04-28 07:19 UTC, ntruchsess commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> -        if (result.OfferStatusId != OfferStatusId.IN_REVIEW)
fixed

2023-04-28 07:32 UTC, merged