bugfix(authentication): fix config errors on initialization
catenax-ng/tx-portal-backend pull request #358
Opened 2023-04-28 14:02 UTC by ntruchsess

* add healthchecks to ensure pod is finished initializing config before facing traffic
Refs: CPLP-2567

2023-05-02 08:08 UTC, ntruchsess commented on src/framework/Framework.Web/JwtBearerConfigurationHealthCheck.cs
> +                ServerCertificateCustomValidationCallback = (_,_,_,_) => true
this is a false-positive as sonar ignores the condition that ensures this code is not running on any non-test-environment.

2023-05-02 14:54 UTC, Phil91 requested changes

2023-05-02 14:54 UTC, Phil91 commented on src/framework/Framework.Web/StartupServiceWebApplicationExtensions.cs
> +        app.MapDefaultHealthChecks(app.Configuration.GetSection("HealthChecks").Get<IEnumerable<HealthCheckSettings>>());
we should probably check that the same path isn't used twice

2023-05-02 17:19 UTC, ntruchsess commented on src/framework/Framework.Web/StartupServiceWebApplicationExtensions.cs
> +        app.MapDefaultHealthChecks(app.Configuration.GetSection("HealthChecks").Get<IEnumerable<HealthCheckSettings>>());
done

2023-05-02 17:28 UTC, ntruchsess commented
Unfortunately WebApplication is a sealed class that cannot be faked, therefore unit-test-coverage cannot easily be increased.

2023-05-03 06:11 UTC, Phil91 approved these changes

2023-05-03 06:32 UTC, merged