CPLP-1898-Delete-TaxId-Attribute-CompanyTable
catenax-ng/tx-portal-backend pull request #37
Opened 2022-12-28 07:45 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1898

2023-01-02 07:27 UTC, Phil91 requested changes
Changes look good so far, please add the missing migration.

2023-01-02 07:27 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +}
Please readd the linebreak

2023-01-02 07:29 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +}
Still I am working on this facing some issue because unit test are failing

2023-01-03 05:32 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +}
Issue is fixed now

2023-01-03 06:58 UTC, Phil91 approved these changes

2023-01-03 07:18 UTC, merged