feature/CPLP-1831-getapplication-refactoring-companyrole
catenax-ng/tx-portal-backend pull request #38
Opened 2022-12-28 13:43 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1831

2022-12-29 09:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetails.cs
> +    public IEnumerable<string>? CompanyRoles { get; set; }
Remove nullable. change it from nullable to non nullable

2022-12-29 10:09 UTC, qxz2mqe commented on src/administration/Administration.Service/Controllers/RegistrationController.cs
> +    /// Example: GET: api/administration/registration/applications?companyName=Car&amp;page=0&amp;size=4&amp;companyApplicationStatus=Closed <br />
why this filter is required here?

2022-12-29 10:52 UTC, qxz2mqe commented on tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> -
Remove all blank spaces

2023-01-02 11:54 UTC, Phil91 requested changes
Only small formatting issues

2023-01-02 11:54 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> +        result.Content.Should().HaveCount(5);
please remove whitespaces

2023-01-02 11:54 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        }
please add a linebreak

2023-01-02 11:54 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .SingleOrDefaultAsync();
please remove whitespaces

2023-01-04 08:11 UTC, Phil91 requested changes

2023-01-04 08:11 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetails.cs
> +    [JsonPropertyName("companyRoles")]
Please add the CompanyRoles to the constructor. If they are optional initialize with =new List<string>()

2023-01-05 07:32 UTC, Phil91 approved these changes

2023-01-05 07:32 UTC, merged