feature(apps)- get provided subscription-status
catenax-ng/tx-portal-backend pull request #383
Opened 2023-05-11 06:24 UTC by qxz2mqe

add leadImage in response of apps provided subscription-status enpoint
apps/provided/subscription-status

ref:-CPLP-2646

2023-05-11 06:47 UTC, Phil91 submitted a review, later dismissed

2023-05-11 06:47 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                    Image = g.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.APP_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => documen
The check should be image status == locked, otherwise you'd be able to receive an pending image

```suggestion
                    Image = g.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.APP_LEADIMAGE && document.DocumentStatusId == DocumentStatusId.LOCKED).Select(document => document.Id).FirstOrDefault()
```

2023-05-11 11:39 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                    Image = g.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.APP_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => documen
fixed

2023-05-11 17:04 UTC, ntruchsess requested changes
see my comment about default-value of ImageId

2023-05-11 17:05 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                    Image = g.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.APP_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => documen
apparently my remark about default-value of Guid being Guid.Empty is not fixed.

2023-05-12 11:13 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                    Image = g.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.APP_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => documen
fixed

2023-05-13 09:38 UTC, ntruchsess requested changes

2023-05-15 06:43 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +            foreach(var item in offerCompanySubscriptionResponse!.Data)
fixed

2023-05-15 09:09 UTC, ntruchsess approved these changes

2023-05-15 09:13 UTC, merged