feature/CPLP-1855 getapplication refactoring filter
catenax-ng/tx-portal-backend pull request #39
Opened 2022-12-28 17:27 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1855

2022-12-29 10:57 UTC, qxz2mqe commented on src/registration/Registration.Service/Controllers/RegistrationController.cs
> +        /// <remarks>Example: Post: /api/registration/application/submitRegistration</remarks>
Why the changes required here for CPLP-1855?

2022-12-29 10:58 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> -
Why changes is required here for CPLP-1855? Revert the changes

2023-01-02 07:24 UTC, Phil91 requested changes

2023-01-02 07:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        IEnumerable<CompanyApplicationStatusId>? companyApplicationStatusId =new[] { CompanyApplicationStatusId.SUBMITTED, CompanyApplicationStatusId.CONFIRMED, CompanyApplicationStatusId.DECLINED };
The ? isn't necessary since a value is directly assigned.

2023-01-02 07:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +    public Task<Pagination.Response<CompanyApplicationDetails>> GetCompanyApplicationDetailsAsync(int page, int size,CompanyApplicationStatusFilter? companyApplicationStatus = null, string? companyNa
please rename `companyApplicationStatus` to `companyApplicationStatusFilter`

2023-01-02 07:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +    private static IEnumerable<CompanyApplicationStatusId> UpdateCompanyApplicationStatusId(CompanyApplicationStatusFilter? companyApplicationStatusFilter = null)
Please rename the method to `GetCompanyApplicationStatusId` for a better understanding, since it isn't updating the status

2023-01-02 07:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (companyApplicationStatusFilter!.Equals(CompanyApplicationStatusFilter.Closed))
this will throw an error if companyApplicationStatusFilter is null. Please add a check for `companyApplicationStatusFilter == null`

2023-01-02 07:24 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .SingleOrDefaultAsync();
Please remove whitespaces

2023-01-02 11:57 UTC, Phil91 requested changes

2023-01-02 11:57 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        IEnumerable<CompanyApplicationStatusId> companyApplicationStatusId = default!;
just recognized we don't need to have the variable, we can directly return the values.

2023-01-02 14:01 UTC, Phil91 requested changes

2023-01-02 14:01 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        switch(companyApplicationStatusFilter)
the null case with the default values is now missing

2023-01-02 14:27 UTC, VPrasannaK94 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        switch(companyApplicationStatusFilter)
default case: will achieve the null and default condition

2023-01-03 06:53 UTC, Phil91 approved these changes

2023-01-03 06:56 UTC, Phil91 commented on src/registration/Registration.Service/Controllers/RegistrationController.cs
> +        /// <remarks>Example: Post: /api/registration/application/submitRegistration</remarks>
fixed

2023-01-03 06:57 UTC, merged