CPLP-1899-add-new-table-for-uniqueidentifier
catenax-ng/tx-portal-backend pull request #52
Opened 2023-01-04 10:59 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1899

2023-01-04 14:05 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230104130412_CPLP-1899-AddUniqueIdentifiersTable.Designer.cs
> +﻿// <auto-generated />
Please add the fileheader

2023-01-04 14:05 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Please readd the file header

2023-01-05 07:18 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
fixed

2023-01-05 07:18 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230104130412_CPLP-1899-AddUniqueIdentifiersTable.Designer.cs
> +﻿// <auto-generated />
fixed

2023-01-05 07:18 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230104130412_CPLP-1899-AddUniqueIdentifiersTable.cs
> +﻿using System;
fixed

2023-01-05 07:56 UTC, Phil91 requested changes
There are some values missing in the country_assigned_identifiers. Additionally I'm not sure if the values in the company_identifiers jsons are correct and would like @jjeroch to confirm

2023-01-05 07:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identifiers.consortia.json
> +      "company_id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f88",
@jjeroch are those values correct?

2023-01-05 07:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_assigned_identifiers.json
> +    {
Please provide the missing values from the story as well

2023-01-05 07:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identifiers.json
> +      "company_id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f87",
@jjeroch same question here, correct values?

2023-01-05 08:30 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identifiers.consortia.json
> +      "company_id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f88",
I will quickly check the numbers and do a correction of the values

2023-01-05 08:38 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identifiers.json
> +      "company_id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f87",
updated :)

2023-01-05 08:38 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_identifiers.consortia.json
> +      "company_id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f88",
updated

2023-01-05 08:40 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_assigned_identifiers.json
> +    {
@qxz2mqe please add the value "DE" with the unique_identifier_id "2". Otherwise the example data mismatch with the supported country_assigned_identifiers.

2023-01-05 09:27 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_assigned_identifiers.json
> +    {
fixed

2023-01-05 10:34 UTC, Phil91 approved these changes

2023-01-05 11:23 UTC, merged