CPLP-1965 checklist wallet
catenax-ng/tx-portal-backend pull request #72
Opened 2023-01-10 15:04 UTC by Phil91

2023-01-12 13:31 UTC, evegufy commented on .github/workflows/trivy.yml
> +          output: "trivy-results6.sarif"
the output also needs to be set to 'trivy-results11.sarif'

2023-01-12 13:33 UTC, Phil91 commented on .github/workflows/trivy.yml
> +          output: "trivy-results6.sarif"
thanks, missed it. adjusted.

2023-01-12 13:36 UTC, evegufy requested changes

2023-01-12 13:36 UTC, evegufy commented on .github/workflows/release.yml
> +          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_MAINTENANCE }}
the env var IMAGE_NAME_CHECKLIST_WORKER needs to added at the top in line 20 and then used here.

2023-01-12 13:36 UTC, evegufy commented on .github/workflows/release.yml
> +          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_MAINTENANCE }}:${{ steps.git-tag.outputs.git-version }}
the env var IMAGE_NAME_CHECKLIST_WORKER needs to added at the top in line 20 and then used here.

2023-01-12 14:52 UTC, Phil91 commented on .github/workflows/release.yml
> +          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_MAINTENANCE }}:${{ steps.git-tag.outputs.git-version }}
changed

2023-01-12 14:52 UTC, Phil91 commented on .github/workflows/release.yml
> +          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_MAINTENANCE }}
changed

2023-01-12 15:31 UTC, evegufy commented on docker/Dockerfile-checklist-worker
> +COPY src/portalbackend/PortalBackend.PortalEntities/ src/portalbackend/PortalBackend.PortalEntities/
I just had a look at the transitive dependencies:

   > Org.Eclipse.TractusX.Portal.Backend.Checklist.Library                              1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Cors                                 1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.DBAccess                             1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.ErrorHandling                        1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Models                               1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Seeding                              1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Swagger                              1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Token                                1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Framework.Web                                  1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Keycloak.Authentication                        1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling                         1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Keycloak.Factory                               1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library                               1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.PortalBackend.DBAccess                         1.0.0   
   > Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities                   1.0.0   

You'd probably need to copy the entire portalbackend as well as framework and keycloak.

2023-01-16 07:52 UTC, Phil91 commented on docker/Dockerfile-checklist-worker
> +COPY src/portalbackend/PortalBackend.PortalEntities/ src/portalbackend/PortalBackend.PortalEntities/
docker file adjusted

2023-01-16 08:48 UTC, evegufy approved these changes
lgtm

2023-01-17 17:15 UTC, ntruchsess requested changes

2023-01-17 17:15 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                        application.ApplicationChecklist.Select(x => new ApplicationChecklistEntryDetails(x.ApplicationChecklistEntryTypeId, x.ApplicationChecklistEntryStatusId)))
this query now joins multiple tables selecting multiple entries from each. We should therefore use AsSplitQuery()

2023-01-17 17:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationChecklistRepository.cs
> +            .ToDictionaryAsync(x => x.Item1, x => x.Item2);
For consistency with other queries please return AsAsyncEnumerable. ToDictionary will not be executed on the database anyway and can be done in the businesslogic with no negative impact.

2023-01-17 17:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                 ca.ApplicationChecklist
```ca.ApplicationChecklist.SingleOrDefault(x => x.ApplicationChecklistEntryTypeId == checklistEntryTypeId)!.ApplicationChecklistEntryStatusId)```

2023-01-18 08:38 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230110173628_CPLP-1963-AddChecklist.cs
> +﻿/********************************************************************************
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +        var createdWallet = true;
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +            throw new ControllerArgumentException("User is not assigned to company", nameof(iamUserId));
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +    private async Task CheckCanRunStepAsync(Guid applicationId, ApplicationChecklistEntryTypeId step, ApplicationChecklistEntryStatusId[] allowedStatus)
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +        currentStatus.TryGetValue(ApplicationChecklistEntryTypeId.BUSINESS_PARTNER_NUMBER, out var bpnStatus);
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +            throw new ConflictException($"{ApplicationChecklistEntryTypeId.BUSINESS_PARTNER_NUMBER} is not available as next step");
absolutely. changed it

2023-01-18 08:38 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyApplication.cs
> +    public virtual ICollection<ApplicationChecklistEntry> ApplicationChecklist { get; private set; }
done

2023-01-18 08:38 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +    public async Task<bool> CreateWalletAsync(Guid applicationId, CancellationToken cancellationToken)
done

2023-01-18 08:38 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetails.cs
>  namespace Org.Eclipse.TractusX.Portal.Backend.PortalBackend.DBAccess.Models;
done

2023-01-18 08:38 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                        application.ApplicationChecklist.Select(x => new ApplicationChecklistEntryDetails(x.ApplicationChecklistEntryTypeId, x.ApplicationChecklistEntryStatusId)))
done

2023-01-18 08:38 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationChecklistRepository.cs
> +            .ToDictionaryAsync(x => x.Item1, x => x.Item2);
done

2023-01-18 08:38 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                 ca.ApplicationChecklist
had the implementation like this before, but it will throw an exception if for some reason the checklist isn't correctly or not at all created for the application.

2023-01-18 09:44 UTC, Phil91 commented on src/checklist/Checklist.Library/ChecklistService.cs
> +                await CreateWalletAsync(applicationId, cancellationToken).ConfigureAwait(false);
I've unified the error handling

2023-01-18 13:21 UTC, Phil91 commented on src/checklist/Checklist.Worker/ChecklistExecutionService.cs
> +                var checklistEntryData = await portalRepositories.GetInstance<IApplicationChecklistRepository>().GetChecklistDataGroupedByApplicationId(_workerBatchSize).ToListAsync(stoppingToken).Co
changed the implementation to AsyncEnumerable. The processing is slightly changed to have a different db context

2023-01-18 13:22 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationChecklistRepository.cs
> +            .GroupBy(x => x.ApplicationId)
done

2023-01-19 18:19 UTC, ntruchsess approved these changes
I did some cleanup and some refactoring. For consistency all calls to dbContext.SaveAsync() have been removed from the library, Save is now only called at the uppermost level in the Worker resp. BusinessLogic.
Also the lifetime of the inner scoped objects in the worker has been extended by moving the creation of inner scope to outside the loop. Only the dbcontext changetracker is cleared after each processing step. (If there is no memory-leak in ef this should be fine).
Please double-check.
(before merging please double check no other conflicting migration has been merged in the meantime)
There is one outstanding comment I raised but this is not something that really needs to be changed - I'm just curious whether this is actually intended. Feel free to change this in case your answer is 'no' ;-)

2023-01-19 20:12 UTC, jjeroch commented
RC3 is created - this PR can get merged whenever it fits for you @Phil91 & @ntruchsess

2023-01-20 08:02 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    entry.Comment = comment;
the check was unnecessary and wrong. removed it

2023-01-20 08:36 UTC, merged