bug/CPLP-1942-merge-put-post into put request
catenax-ng/tx-portal-backend pull request #82
Opened 2023-01-12 04:46 UTC by VPrasannaK94

https://jira.catena-x.net/browse/CPLP-1942

2023-01-12 11:30 UTC, jjeroch commented
Before merging, Nidhi will need to get informed about the breaking change. Please let me know when it is ready for merge

2023-01-12 15:39 UTC, Phil91 requested changes

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/IServiceProviderBusinessLogic.cs
> +    Task SetServiceProviderCompanyDetailsAsync(ServiceProviderDetailData data, string iamUserId);
Please adjust the comment accordingly to the new functionality of the method

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
>          ValidateServiceProviderDetailData(data);
Can be moved in this method, since we don't have to use it in other methods as well

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +        var serviceProviderDetailDataId = await companyRepository
When calling with a service account user we'd always create the provider company details. the repository call needs to get adjusted for the serviceAccount aka technical user call.

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +            var companyDetails = companyRepository
companyDetails is never used.

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +    /// <inheritdoc />
move to SetServiceProviderCompanyDetailsAsync

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ServiceProviderController.cs
>      /// Updates detail data to the calling users service provider
Please update description to new functionallity

2023-01-12 15:39 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ServiceProviderController.cs
> +    [ProducesResponseType(typeof(int), StatusCodes.Status200OK)]
int is wrong, nothing is currently returned. Not sure whether to return 200, 201, or 204. @ntruchsess what's your opinion?

2023-01-12 15:39 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +    public async Task SetServiceProviderCompanyDetailsAsync_EmptyServiceProviderDetailsId_ReturnsExpectedResult()
Please add assert that the update isn't called and the create was called once

2023-01-12 15:39 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +    public async Task SetServiceProviderCompanyDetailsAsync_WithServiceProviderDetailsId_ReturnsExpectedResult()
please add the assertion that the update was called exactly once and the create wasn't called

2023-01-12 15:48 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +    /// <inheritdoc />
not separating synchronous validation of input parameters from asynchronous code is a code-smell so this should not be moved but stay separate.

2023-01-12 15:50 UTC, ntruchsess commented on src/administration/Administration.Service/Controllers/ServiceProviderController.cs
> +    [ProducesResponseType(typeof(int), StatusCodes.Status200OK)]
empty body in response should be '204 No Content' (as before the change)

2023-01-12 15:56 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +    /// <inheritdoc />
oh, I see that was misleading. just meant the /// <inheritdoc />

2023-01-19 08:06 UTC, Phil91 approved these changes

2023-01-19 08:15 UTC, Phil91 commented
> Before merging, Nidhi will need to get informed about the breaking change. Please let me know when it is ready for merge

@jjeroch ready for merging. @VPrasannaK94 FYI maybe please align with julia before merging.

2023-01-20 04:20 UTC, merged