feature/cplp-231-apps-app-image-document
catenax-ng/tx-portal-backend pull request #83
Opened 2023-01-12 07:14 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-231

2023-01-12 11:29 UTC, jjeroch requested changes

2023-01-12 11:29 UTC, jjeroch commented on src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
> +    /// Retrieve Document Content for Document Type Lead Image and App Lead Image by Id
small adjustment - please write
"Retrieve Document Content for document type "App Lead Image" and "App Image" by ID"

2023-01-12 11:29 UTC, jjeroch commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    /// Get Document Content for Lead Image and App Lead Image DocumentType
same as above

2023-01-12 11:29 UTC, jjeroch commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    /// <response code="400">Document and app id do not match. or Document can not get retrieved. Document type not supported.</response>
Suggestion to change to "Document / App id not found or document type not supported."

2023-01-12 11:29 UTC, jjeroch commented on tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
> +    public async Task GetAppImageDocumentContentAsync_ReturnsExpected()
@qxz2mqe can you please check the unit test scenario.
Ideally I would expect 3 scenarios
#1 => successful case where appId and documentId for a png and jpeg are send and document_content is successfully retrieved
#2 => where appId and documentId are both existing but not matching. Expected Result: error
#3 => where appId and documentId match; even the document_type_id is correct but the document has document type "pdf". Expected Result: error

2023-01-12 11:51 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
> +    /// Retrieve Document Content for Document Type Lead Image and App Lead Image by Id
fixed

2023-01-12 11:51 UTC, qxz2mqe commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    /// Get Document Content for Lead Image and App Lead Image DocumentType
fixed

2023-01-12 11:51 UTC, qxz2mqe commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    /// <response code="400">Document and app id do not match. or Document can not get retrieved. Document type not supported.</response>
fixed

2023-01-12 11:59 UTC, qxz2mqe commented on tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
> +    public async Task GetAppImageDocumentContentAsync_ReturnsExpected()
all the scenario has been covered . we don;t anything document type pdf here we have documenttypeid either it should be App_Image or App_LeadImage then expected result will come for success scenarios other wise if document typeid is "APP_CONTRACT",
      "DATA_CONTRACT",
      "ADDITIONAL_DETAILS",   returned the unit test has been written for that scenarios as well where it will throw the error.
Unit Test has been written for 100% coverage. there are three unit test has been written one for success scenario and two for failure i.e error scenario

2023-01-12 15:02 UTC, ntruchsess requested changes
endpoint is returning incorrect response and content-type. (See comment in controller-class)
please be aware I did some refactoring / cleanup of the database-query adjusting the businesslogic and unit-test. Please pull before proceeding.

2023-01-13 12:28 UTC, qxz2mqe commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    [ProducesResponseType(typeof(AppImageFileContent), StatusCodes.Status200OK)]
fixed

2023-01-16 21:32 UTC, ntruchsess approved these changes

2023-01-16 21:33 UTC, merged