CPLP-1900, CPLP-1901 GET and POST registration company details unique identifiers
catenax-ng/tx-portal-backend pull request #88
Opened 2023-01-13 00:25 UTC by ntruchsess

2023-01-15 17:01 UTC, ntruchsess commented
the remaining 2 code-smells are due to the number of arguments in the new framework-class https://github.com/catenax-ng/tx-portal-backend/blob/feature/CPLP-1900-get-post-company-details-unique-identifiers/src/framework/Framework.DBAccess/ContextExtensions.cs
I don't think those are fixable in a good way. The algorithm covered just requires this number of parameters. Splitting the method into the 3 sub-algorithms would not reduce the number of arguments significantly for each part of the algorithm as most arguments are shared between them. Actually doing so would increase the complexity of the code that makes use of it.

2023-01-16 07:46 UTC, Phil91 requested changes
Just two small things. Logicwise everything looks good.

I really like the AddAttachRemoveRange implementation 👍

2023-01-16 07:46 UTC, Phil91 commented on tests/framework/Framework.DBAccess.Tests/ContextExtensionsTests.cs
> +    private readonly IFixture _fixture;
can be made to local variable

2023-01-16 07:46 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    .Select(identifyer => new ValueTuple<UniqueIdentifierId,string>(identifyer.UniqueIdentifierId, identifyer.Value))))
typo in identifyer -> identifier

2023-01-16 07:55 UTC, ntruchsess commented on tests/framework/Framework.DBAccess.Tests/ContextExtensionsTests.cs
> +    private readonly IFixture _fixture;
sure it can be defined locally. But it's what we do in all unit-test classes which makes it easier for the next developer to add further tests. And in terms of efficiency - as it's a unit-test it doesn't have any impact on the runtime anyway so it' unimportant to temporary spend a few bytes on the heap to be garbage-collected instead allocating on the stack.

2023-01-16 08:05 UTC, merged