CPLP-1904 add company identifier to registration data
catenax-ng/tx-portal-backend pull request #97
Opened 2023-01-16 17:46 UTC by ntruchsess

implements https://jira.catena-x.net/browse/CPLP-1904

2023-01-17 10:03 UTC, Phil91 requested changes

2023-01-17 17:21 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +            .AsSplitQuery()
yes - as the resultset of the database is always a table as soon the data logically spawns more than two dimensions the size will grow big as the numbers of records being returned by each dimension do multiply.
(any subselect that has multiple results will add another dimension)

2023-01-17 17:23 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    x.Company.CompanyAssignedRoles!.Select(companyAssignedRole => companyAssignedRole.CompanyRoleId),
fixed

2023-01-17 17:24 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                    x.Company.CompanyUsers.SelectMany(companyUser => companyUser!.Documents!.Where(document=>documentTypes.Contains(document.DocumentTypeId)).Select(document => document.DocumentName)
fixed

2023-01-17 17:26 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            data.DocumentNames.Select(name => new RegistrationDocumentNames(name)),
agree - this is from preexisting code. I didn't want to change the api-endpoint in an incompatible way. I'll clarify with @Julia whether this is really intended

2023-01-17 17:38 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTest.cs
> +    public async Task GetRegistrationDataUntrackedAsync_WithApplicationIdAndDocumentType_ReturnsExpectedResult()
implemented

2023-01-18 07:15 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +            .AsSplitQuery()
thanks for the explination

2023-01-18 07:16 UTC, Phil91 approved these changes

2023-01-18 07:42 UTC, merged