Feature/cplp-1975-remove-offer-thumbnailurl
catenax-ng/tx-portal-backend pull request #98
Opened 2023-01-18 06:15 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1975

2023-01-18 22:01 UTC, ntruchsess requested changes

2023-01-19 08:30 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditOffer20221013.cs
> -    public string? ThumbnailUrl { get; set; }
fixed

2023-01-19 12:41 UTC, ntruchsess requested changes

2023-01-19 12:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230119082324_CPLP-1975-RemoveOfferThumbnailUrl.cs
> +﻿using System;
header comment is missing

2023-01-19 12:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
header comment is missing

2023-01-19 12:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230119082324_CPLP-1975-RemoveOfferThumbnailUrl.Designer.cs
> +﻿// <auto-generated />
header comment is missing

2023-01-20 09:08 UTC, merged