CPLP-1903 access bpdm endpoint getLegalEntities by Bpn
catenax-ng/tx-portal-backend pull request #99
Opened 2023-01-18 14:46 UTC by ntruchsess

2023-01-18 16:59 UTC, jjeroch commented on src/portalbackend/PortalBackend.PortalEntities/Enums/BpdmIdentifierId.cs
> +    CDQID = 3,
@ntruchsess sollen wir wirklich die IDs aufnehmen, die wir eh nicht weiter verarbeiten? Ich kann verstehen, dass es zur Vollständigkeit hilft, aber ist es notwendig, wenn wir BPDM Identifier wie "CX_POOL_ID" eh ignorieren?

2023-01-19 23:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Enums/BpdmIdentifierId.cs
> +    CDQID = 3,
@jjeroch : könnte man auch weglassen, schadet aber auch nichts.

2023-01-20 09:06 UTC, ntruchsess commented
please ignore the 3 code-smells, those are on purpose and shall be resolved in follow-up tickets after FE is adjusted to new endpoint / missing information about bpdm-response-semantics has been clarified

2023-01-20 09:49 UTC, Phil91 requested changes

2023-01-20 09:49 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +            .Where(identifier => identifier.CountryAlpha2Code == countryAlpha2Code && identifier.BpdmIdentifierId != null && bpdmIdentifierIds.Contains(identifier.BpdmIdentifierId.Value))
I've read that the performance of contains for database queries is only better up to 50 items, as soon as you query for more than 50 any is better. I'll look that up and send it to you

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
can't we maybe use clientId / secret authentication for that? then we could use our token service and not have to use the user's secret.

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +    public async Task<IEnumerable<BpdmLegalEntityDto>> FetchLegalEntities(FetchLegalEntitiesQueryParameters parameters, string token, CancellationToken cancellationToken)
This method is currently not used besids of Tests?

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +        else
else can be removed, because we either return or throw error in the if statement

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +            Path = $"api/catena/legal-entities/legal-addresses/search"
$ can be removed

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ConflictException($"Bpdm did return incorrect bpn legal-entity-data");
$ can be removed

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ConflictException($"Bpdm did return incorrect bpn address-data");
$ can be removed

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!businessPartnerNumber.Equals(legalEntity?.Bpn, StringComparison.OrdinalIgnoreCase))
since legalEntity can't be null ? can be removed

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        BpdmLegalEntityAddressDto? legalEntityAddress;
can't this be assigned directly? the null error handling should happen in the service call

2023-01-20 09:49 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        BpdmNameDto? name;
maybe we can make a single method to check the values, like:

`
    private static T? SingleEntryCheck<T>(Func<BpdmLegalEntityDto, T?> selector, string businessPartnerNumber, BpdmLegalEntityDto legalEntity, string s)
    {
        try
        {
            return selector.Invoke(legalEntity);
        }
        catch (InvalidOperationException)
        {
            throw new ConflictException($"bpdm returned more than a single {s} in legal entity for {businessPartnerNumber}");
        }
    }
`

which than could be used like:

`        var name = SingleEntryCheck<BpdmNameDto?>((x) => x.Names.SingleOrDefault(), businessPartnerNumber, legalEntity, "name");
`

please ignore the name 😆

2023-01-20 10:06 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +            .Where(identifier => identifier.CountryAlpha2Code == countryAlpha2Code && identifier.BpdmIdentifierId != null && bpdmIdentifierIds.Contains(identifier.BpdmIdentifierId.Value))
that is unlikely to be an issue here. Number of bpdmIdentifierIds (types of identifiers being used by bpdm) will be small

2023-01-20 10:07 UTC, ntruchsess commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
sure we could do this, but it's not in the scope of this ticket. @jjeroch may clarify and create follow-up-ticket if this should be changed.

2023-01-20 10:47 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        BpdmNameDto? name;
nice suggestion :-)

2023-01-20 10:55 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!businessPartnerNumber.Equals(legalEntity?.Bpn, StringComparison.OrdinalIgnoreCase))
done

2023-01-20 10:56 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ConflictException($"Bpdm did return incorrect bpn address-data");
done

2023-01-20 10:57 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ConflictException($"Bpdm did return incorrect bpn legal-entity-data");
done

2023-01-20 10:57 UTC, ntruchsess commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +            Path = $"api/catena/legal-entities/legal-addresses/search"
done

2023-01-20 10:58 UTC, ntruchsess commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +        else
done

2023-01-20 11:06 UTC, ntruchsess commented on src/registration/Registration.Service/Bpn/BpnAccess.cs
> +    public async Task<IEnumerable<BpdmLegalEntityDto>> FetchLegalEntities(FetchLegalEntitiesQueryParameters parameters, string token, CancellationToken cancellationToken)
removed redundant initial implementation using incorrect bpdm-endpoint

2023-01-20 11:29 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        BpdmNameDto? name;
thanks :)

2023-01-20 11:42 UTC, Phil91 approved these changes

2023-01-20 11:47 UTC, merged